### PR TITLE
Add support for ECR images

### PR DESCRIPTION
**Pull request by reedloden**
Proposed changes by the FedRAMP PMO in https://www.fedramp.gov/vulnerability-scanning-requirements-for-the-deployment-and-use-of-containers/ include:

> **Asset Management and Inventory Reporting for Deployed Containers**: A unique asset identifier
> must be assigned to every image which corresponds to one or more production-deployed
> containers. These image-based asset identifiers must be documented in the FedRAMP Integrated
> Inventory Workbook Template. Instances of production-deployed containers must be tracked
> internally by the CSP via an automated mechanism, which must be validated by a 3PAO to meet the
> baseline control CM-8. Every production-deployed container must correspond to the image from
> which the deployed container originated, in order to identify the total number of relevant
> vulnerabilities on production associated with that container. While individually deployed instances of
> containers should be tracked internally by the CSP, they do not need to be included as part of the
> FedRAMP Integrated Inventory Workbook Template, unless they are specifically the target of a scan
> performed by a security sensor. If they are the target of a scan performed by a security sensor, they
> must be included as part of the FedRAMP Integrated Inventory Workbook Template ConMon
> deliverable, in accordance with the Guide for Determining Eligibility and Requirements for the Use of
> Sampling for Vulnerability Scans document if applicable.

### CODE REVIEW

**Comment by reedloden** [comment]
I'll rebase this once #139 lands, but just wanted to post it.

**Comment by reedloden** [comment]
@itmecho After this one lands, can we do a release, please? :-)

**Review by itmecho — APPROVED** [review]
Thanks! I'll get a release pushed out for you. 

If you get more feedback from the PMO, don't hesitate to open issues/PRs so we can get the tool up to scratch!

**Comment by itmecho** [comment]
@reedloden having some issues with the travis deployment and the backlog is causing builds to take ages. Looks like I'm going to have to pick this up tomorrow morning. Hopefully we have some binaries then!

**Pull request merged**
